"""Turn aggregation output into the frontend-facing visualization spec.

This stage is pure formatting: it renames, orders, and annotates values that
already exist. It never computes a measure and never reaches for a record --
citations come from :mod:`app.services.citations`, values from
:mod:`app.services.aggregate`.

Titles are built from templates over the plan's own entities rather than
generated by the LLM, so a chart's caption cannot describe something other than
what the data shows.
"""

from __future__ import annotations

from typing import Any

from app.models.schemas import (
    AggregationResult,
    Encoding,
    FieldRef,
    NetworkResult,
    QueryPlan,
    VisualizationSpec,
)
from app.services.citations import build_citations
from app.services.dimensions import Dimension
from app.services.store import StudyStore

#: Key holding the measured value in every chart-family data row.
VALUE_FIELD = "trial_count"


#: Beyond this, a title stops being readable; the count carries the rest.
_MAX_TITLE_VALUES = 3


def _join(values: list[str]) -> str:
    """Render a set of searched values the way the query treats them: a union.

    Naming only the first was a correct chart with a misleading caption --
    "Pembrolizumab trials" over a chart of pembrolizumab *or* nivolumab trials.
    """
    if not values:
        return ""
    if len(values) == 1:
        return values[0]
    if len(values) <= _MAX_TITLE_VALUES:
        return f"{', '.join(values[:-1])} or {values[-1]}"
    shown = ", ".join(values[:_MAX_TITLE_VALUES])
    return f"{shown} or {len(values) - _MAX_TITLE_VALUES} more"


def applied_scope(plan: QueryPlan) -> str:
    """The population actually being measured, as a noun phrase.

    One canonical description derived from the plan itself -- never asked of
    the LLM, and never rebuilt per call site -- so a caption cannot describe
    something other than what was queried. Every applied value appears: naming
    only the first drug captioned a pembrolizumab-*or*-nivolumab chart as
    "Pembrolizumab trials", and country and year filters were invisible.

    'Pembrolizumab or Nivolumab trials in melanoma (phase 3, 2018-2024)'
    """
    entities = plan.entities
    if plan.compare_entities:
        head = " vs ".join(plan.compare_entities)
    elif entities.drugs:
        head = _join(entities.drugs)
    elif entities.conditions:
        head = _join(entities.conditions)
    else:
        head = ""

    qualifiers: list[str] = []
    if entities.conditions and head != _join(entities.conditions):
        qualifiers.append(f"in {_join(entities.conditions)}")
    if entities.sponsors:
        qualifiers.append(f"sponsored by {_join(entities.sponsors)}")
    if entities.countries:
        qualifiers.append(f"in {_join(entities.countries)}")
    # Statuses are held as API enum values (RECRUITING, ACTIVE_NOT_RECRUITING)
    # so they can be matched against records; a title is for a reader.
    status_bits = [s.replace("_", " ").lower() for s in sorted(entities.statuses)]
    status_bits += [
        f"not {s.replace('_', ' ').lower()}" for s in sorted(plan.excluded_statuses)
    ]
    phase_bits = [str(p) for p in sorted(entities.phases)]
    detail = status_bits + ([f"phase {', '.join(phase_bits)}"] if phase_bits else [])
    years = entities.year_range
    if years and (years.start is not None or years.end is not None):
        if years.start is not None and years.end is not None:
            detail.append(f"{years.start}–{years.end}")
        elif years.start is not None:
            detail.append(f"from {years.start}")
        else:
            detail.append(f"to {years.end}")
    if detail:
        qualifiers.append(f"({', '.join(detail)})")

    # "trials" sits right after the head, so qualifiers read as qualifiers:
    # "Pembrolizumab trials in the United States", not "Pembrolizumab in the
    # United States trials".
    phrase = " ".join(part for part in [f"{head} trials" if head else "", *qualifiers] if part)
    phrase = phrase.strip()
    if not phrase:
        return "Clinical trials"
    return phrase[:1].upper() + phrase[1:]


def build_title(plan: QueryPlan, dimension: Dimension) -> str:
    subject = applied_scope(plan)
    if plan.viz_type == "time_series":
        return f"{subject} by start year"
    return f"{subject} by {dimension.axis_label.lower()}"


def build_chart_spec(
    result: AggregationResult,
    plan: QueryPlan,
    dimension: Dimension,
    store: StudyStore,
) -> VisualizationSpec:
    """Bar / time series / grouped bar / geographic / histogram.

    One code path serves all five, because by this point they differ only in
    the ``type`` string and whether a ``color`` channel is present.
    """
    rows: list[dict[str, Any]] = []
    for datum in result.data:
        citations, total = build_citations(
            datum.nct_ids,
            store,
            result.dimension,
            limit=plan.max_citations_per_datum,
        )
        row: dict[str, Any] = {
            result.dimension: datum.key,
            VALUE_FIELD: datum.value,
        }
        if datum.series is not None:
            row["series"] = datum.series
        row["citations"] = [c.model_dump() for c in citations]
        row["total_supporting_trials"] = total
        rows.append(row)

    encoding = Encoding(
        x=FieldRef(
            field=result.dimension,
            label=dimension.axis_label,
            type=dimension.field_type,
        ),
        y=FieldRef(field=VALUE_FIELD, label="Number of trials", type="quantitative"),
        color=(
            FieldRef(field="series", label="Series", type="nominal")
            if result.series_dimension
            else None
        ),
    )
    return VisualizationSpec(
        type=plan.viz_type,
        title=build_title(plan, dimension),
        encoding=encoding,
        data=rows,
    )


NODE_KEY_MAP = {
    "id": "id",
    "label": "label",
    "size": "size",
    "group": "kind",
    # Present on every node (null when unresolved) so a frontend can link
    # out to RxNav without probing for the key.
    "rxcui": "rxcui",
}
EDGE_KEY_MAP = {"source": "source", "target": "target", "weight": "weight"}


def build_network_spec(
    result: NetworkResult, plan: QueryPlan, store: StudyStore
) -> VisualizationSpec:
    """Network graph.

    ``data`` stays a ``list[dict]`` so one response model covers every chart
    type; the single row holds the node and edge collections, and
    ``encoding.nodes`` / ``encoding.edges`` document which key means what so a
    frontend can wire it to d3-force or cytoscape without guessing.
    """
    limit = plan.max_citations_per_datum

    nodes: list[dict[str, Any]] = []
    for node in result.nodes:
        citations, total = build_citations(
            node.nct_ids, store, "drug" if node.kind == "drug" else "sponsor", limit=limit
        )
        nodes.append(
            {
                "id": node.id,
                "label": node.label,
                "kind": node.kind,
                "size": node.size,
                # RxNorm identity and the source names folded into this node, so
                # a merge is visible to the reader and checkable against RxNav.
                "rxcui": node.rxcui,
                "merged_from": node.merged_from,
                "citations": [c.model_dump() for c in citations],
                "total_supporting_trials": total,
            }
        )

    edges: list[dict[str, Any]] = []
    for edge in result.edges:
        # An edge's evidence is the set of trials containing *both* endpoints,
        # so the excerpt has to show both. For a drug-drug edge the
        # intervention list covers them; for a sponsor-drug edge it proves only
        # the drug end, so the lead sponsor is quoted alongside it.
        edge_evidence = "sponsor_drug" if result.kind == "sponsor_drug" else "drug"
        citations, total = build_citations(
            edge.nct_ids, store, edge_evidence, limit=limit
        )
        edges.append(
            {
                "source": edge.source,
                "target": edge.target,
                "weight": edge.weight,
                "citations": [c.model_dump() for c in citations],
                "total_supporting_trials": total,
            }
        )

    subject = applied_scope(plan)
    kind_label = (
        "Drug co-occurrence network" if result.kind == "drug_drug"
        else "Sponsor-drug network"
    )
    title = f"{kind_label} for {subject[:1].lower() + subject[1:]}"

    return VisualizationSpec(
        type="network_graph",
        title=title,
        encoding=Encoding(nodes=NODE_KEY_MAP, edges=EDGE_KEY_MAP),
        data=[{"nodes": nodes, "edges": edges}],
    )
