"""Turn aggregation output into the frontend-facing visualization spec.

This stage is pure formatting: it renames, orders, and annotates values that
already exist. It never computes a measure and never reaches for a record --
citations come from :mod:`app.services.citations`, values from
:mod:`app.services.aggregate`.

Titles are built from templates over the plan's own entities rather than
generated by the LLM, so a chart's caption cannot describe something other than
what the data shows.
"""

from __future__ import annotations

from typing import Any

from app.models.schemas import (
    AggregationResult,
    Encoding,
    FieldRef,
    NetworkResult,
    QueryPlan,
    VisualizationSpec,
)
from app.services.citations import build_citations
from app.services.dimensions import Dimension
from app.services.store import StudyStore

#: Key holding the measured value in every chart-family data row.
VALUE_FIELD = "trial_count"


def _entity_phrase(plan: QueryPlan) -> str:
    """What was searched for, as a noun phrase: 'Pembrolizumab trials in melanoma'.

    Built from the plan's own entities rather than asked of the LLM, so a
    chart's caption can never describe something other than what was queried.
    """
    entities = plan.entities
    if plan.compare_entities:
        head = " vs ".join(plan.compare_entities)
    elif entities.drugs:
        head = entities.drugs[0]
    elif entities.conditions:
        head = entities.conditions[0]
    else:
        head = ""

    qualifiers: list[str] = []
    if entities.conditions and head != entities.conditions[0]:
        qualifiers.append(f"in {entities.conditions[0]}")
    if entities.sponsors:
        qualifiers.append(f"sponsored by {entities.sponsors[0]}")
    if entities.statuses:
        qualifiers.append(f"({', '.join(sorted(entities.statuses))})")
    if entities.phases:
        qualifiers.append(f"(phase {', '.join(str(p) for p in sorted(entities.phases))})")

    phrase = " ".join(part for part in [head, *qualifiers] if part).strip()
    return phrase[:1].upper() + phrase[1:] if phrase else ""


def build_title(plan: QueryPlan, dimension: Dimension) -> str:
    subject = _entity_phrase(plan)
    subject = f"{subject} trials" if subject else "Clinical trials"
    if plan.viz_type == "time_series":
        return f"{subject} by start year"
    return f"{subject} by {dimension.axis_label.lower()}"


def build_chart_spec(
    result: AggregationResult,
    plan: QueryPlan,
    dimension: Dimension,
    store: StudyStore,
) -> VisualizationSpec:
    """Bar / time series / grouped bar / geographic / histogram.

    One code path serves all five, because by this point they differ only in
    the ``type`` string and whether a ``color`` channel is present.
    """
    rows: list[dict[str, Any]] = []
    for datum in result.data:
        citations, total = build_citations(
            datum.nct_ids,
            store,
            result.dimension,
            limit=plan.max_citations_per_datum,
        )
        row: dict[str, Any] = {
            result.dimension: datum.key,
            VALUE_FIELD: datum.value,
        }
        if datum.series is not None:
            row["series"] = datum.series
        row["citations"] = [c.model_dump() for c in citations]
        row["total_supporting_trials"] = total
        rows.append(row)

    encoding = Encoding(
        x=FieldRef(
            field=result.dimension,
            label=dimension.axis_label,
            type=dimension.field_type,
        ),
        y=FieldRef(field=VALUE_FIELD, label="Number of trials", type="quantitative"),
        color=(
            FieldRef(field="series", label="Series", type="nominal")
            if result.series_dimension
            else None
        ),
    )
    return VisualizationSpec(
        type=plan.viz_type,
        title=build_title(plan, dimension),
        encoding=encoding,
        data=rows,
    )


NODE_KEY_MAP = {"id": "id", "label": "label", "size": "size", "group": "kind"}
EDGE_KEY_MAP = {"source": "source", "target": "target", "weight": "weight"}


def build_network_spec(
    result: NetworkResult, plan: QueryPlan, store: StudyStore
) -> VisualizationSpec:
    """Network graph.

    ``data`` stays a ``list[dict]`` so one response model covers every chart
    type; the single row holds the node and edge collections, and
    ``encoding.nodes`` / ``encoding.edges`` document which key means what so a
    frontend can wire it to d3-force or cytoscape without guessing.
    """
    limit = plan.max_citations_per_datum

    nodes: list[dict[str, Any]] = []
    for node in result.nodes:
        citations, total = build_citations(
            node.nct_ids, store, "drug" if node.kind == "drug" else "sponsor", limit=limit
        )
        nodes.append(
            {
                "id": node.id,
                "label": node.label,
                "kind": node.kind,
                "size": node.size,
                "citations": [c.model_dump() for c in citations],
                "total_supporting_trials": total,
            }
        )

    edges: list[dict[str, Any]] = []
    for edge in result.edges:
        # An edge's evidence is the set of trials containing *both* endpoints,
        # so the drug-name field is what a reader should check.
        citations, total = build_citations(edge.nct_ids, store, "drug", limit=limit)
        edges.append(
            {
                "source": edge.source,
                "target": edge.target,
                "weight": edge.weight,
                "citations": [c.model_dump() for c in citations],
                "total_supporting_trials": total,
            }
        )

    subject = _entity_phrase(plan)
    if result.kind == "drug_drug":
        title = f"Drug co-occurrence network{f' for {subject} trials' if subject else ''}"
    else:
        title = f"Sponsor-drug network{f' for {subject} trials' if subject else ''}"

    return VisualizationSpec(
        type="network_graph",
        title=title,
        encoding=Encoding(nodes=NODE_KEY_MAP, edges=EDGE_KEY_MAP),
        data=[{"nodes": nodes, "edges": edges}],
    )
